project:
  type: website

profile:
  default: english
  group: [english, czech]

execute:
  freeze: true

website:
  repo-url: https://github.com/martinfleis/sds/
  repo-actions: [issue]
  sidebar:
    style: "floating"
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - about.qmd
      - section: "Layout"
        contents:
          - 01_infra_test.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/martinfleis
      - icon: github
        href: https://github.com/martinfleis/sds
  page-navigation: true
  page-footer:
    center: "Course material by Martin Fleischmann. Available under CC-BY-SA 4.0."
  search:
    location: sidebar
    type: overlay

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    highlight-style: gruvbox
