project:
  type: website

profile:
  default: english
  group: [english, czech]

execute:
  freeze: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    toc: true
    smooth-scroll: true
    highlight-style: atom-one

website:
  repo-url: https://github.com/martinfleis/sds/
  favicon: assets/favicon.png
  repo-actions: [issue]
  twitter-card: true
  page-navigation: true
  page-footer:
    center: "Course material by Martin Fleischmann. Available under CC-BY-SA 4.0."
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 1
    logo: assets/logo.svg
    tools:
      - icon: twitter
        href: https://twitter.com/martinfleis
      - icon: github
        href: https://github.com/martinfleis/sds
    contents:
      - section: "Course information"
        contents:
          - text: "Overview"
            file: index.qmd
          - chapter_00/infrastructure.qmd
          - chapter_00/assignment.qmd
      - text: "---"
      - section: "Introduction"
        contents:
          - chapter_01/concepts.qmd
          - chapter_01/hands_on.qmd
          - chapter_01/exercise.qmd
      - section: "Open Data Science"
        contents:
          - chapter_02/concepts.qmd
          - chapter_02/hands_on.qmd
          - chapter_02/exercise.qmd
      - section: "Spatial data"
        contents:
          - chapter_03/concepts.qmd
          - chapter_03/hands_on.qmd
          - chapter_03/exercise.qmd
      - section: "Spatial weights"
        contents:
          - chapter_04/concepts.qmd
          - chapter_04/hands_on.qmd
          - chapter_04/exercise.qmd
      - section: "Exploratory spatial data analysis"
        contents:
          - chapter_05/concepts.qmd
          - chapter_05/hands_on.qmd
          - chapter_05/exercise.qmd
      - section: "Point patterns"
        contents:
          - chapter_06/concepts.qmd
          - chapter_06/hands_on.qmd
          - chapter_06/exercise.qmd
      - section: "Clustering"
        contents:
          - chapter_07/concepts.qmd
          - chapter_07/hands_on.qmd
          - chapter_07/exercise.qmd
      - section: "Raster data"
        contents:
          - chapter_08/concepts.qmd
          - chapter_08/hands_on.qmd
          - chapter_08/exercise.qmd
      - section: "Inequality"
        contents:
          - chapter_09/concepts.qmd
          - chapter_09/hands_on.qmd
          - chapter_09/exercise.qmd
      - section: "Feature engineering"
        contents:
          - chapter_10/concepts.qmd
          - chapter_10/hands_on.qmd
          - chapter_10/exercise.qmd
      - section: "Regression"
        contents:
          - chapter_11/concepts.qmd
          - chapter_11/hands_on.qmd
          - chapter_11/exercise.qmd
      - section: "Machine learning"
        contents:
          - chapter_12/concepts.qmd
          - chapter_12/hands_on.qmd
          - chapter_12/exercise.qmd


