project:
  type: website
  title: "Spatial Data Science for Social Geography"
  resources:
    - environment.yml
    - "*/slides/*"
    - "*/data/*"
    - "!_site_micro/"
    - "!_site_sds4sg/"

lang: en

execute:
  freeze: false
  cache: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: assets/styles.css
    toc: true
    smooth-scroll: true
    highlight-style: atom-one
    bibliography: assets/references.bib

website:
  repo-url: https://github.com/martinfleis/sds/
  favicon: assets/favicon.png
  repo-actions: [issue]
  twitter-card: true
  page-navigation: true
  page-footer:
    center: "Course material by [Martin Fleischmann](https://martinfleischmann.net). Available under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 1
    logo: assets/logo.svg
    tools:
      - icon: twitter
        href: https://twitter.com/martinfleis
      - icon: github
        href: https://github.com/martinfleis/sds