project:
  title: "Spatial Data Science for Social Geography"
  output-dir: ./_site_sds4sg

website:
  sidebar:
    contents:
      - section: "Course information"
        contents:
          - text: "Overview"
            file: index.qmd
          - chapter_00/infrastructure.qmd
          - chapter_00/assignment.qmd
      - text: "---"
      - section: "Introduction"
        contents:
          - chapter_01/concepts.qmd
          - chapter_01/hands_on.qmd
          - chapter_01/exercise.qmd
      - section: "Open Data Science"
        contents:
          - chapter_02/concepts.qmd
          - chapter_02/hands_on.qmd
          - chapter_02/exercise.qmd
      - section: "Spatial data"
        contents:
          - chapter_03/concepts.qmd
          - chapter_03/hands_on.qmd
          - chapter_03/exercise.qmd
      - section: "Spatial weights"
        contents:
          - chapter_04/concepts.qmd
          - chapter_04/hands_on.qmd
          - chapter_04/exercise.qmd
      - section: "Exploratory spatial data analysis"
        contents:
          - chapter_05/concepts.qmd
          - chapter_05/hands_on.qmd
          - chapter_05/exercise.qmd
      - section: "Point patterns"
        contents:
          - chapter_06/concepts.qmd
          - chapter_06/hands_on.qmd
          - chapter_06/exercise.qmd
      - section: "Clustering"
        contents:
          - chapter_07/concepts.qmd
          - chapter_07/hands_on.qmd
          - chapter_07/exercise.qmd
      - section: "Raster data"
        contents:
          - chapter_08/concepts.qmd
          - chapter_08/hands_on.qmd
          - chapter_08/exercise.qmd
      - section: "Interpolation"
        contents:
          - chapter_09/concepts.qmd
          - chapter_09/hands_on.qmd
          - chapter_09/exercise.qmd
      - section: "Regression"
        contents:
          - chapter_10/concepts.qmd
          - chapter_10/hands_on.qmd
          - chapter_10/exercise.qmd
      - section: "Machine learning"
        contents:
          - chapter_11/concepts.qmd
          - chapter_11/hands_on.qmd
          - chapter_11/exercise.qmd

