project:
  title: "Spatial Data Science in Python"
  output-dir: ./_site_micro

website:
  sidebar:
    contents:
      - section: "Course information"
        contents:
          - text: "Overview"
            file: index.qmd
          - course_information/infrastructure.qmd
          - course_information/assignment.qmd