name: sds
channels:
  - conda-forge
dependencies:
  - python
  # to run the code
  - pandas
  - seaborn
  - openpyxl
  - geopandas
  - pyogrio
  - geopy
  # infrastructure
  - ipykernel
  - jupyter-cache
