name: sds
channels:
  - conda-forge
dependencies:
  - python
  # to run the code
  - pandas
  - seaborn
  - openpyxl
  - geopandas
  - pyogrio
  - geopy
  - contextily
  - pyarrow
  # infrastructure
  - ipykernel
  - jupyter-cache
  - pip
  - pip:
      - git+https://github.com/pysal/libpysal.git@geographs
