name: sds
channels:
  - conda-forge
dependencies:
  - python
  # to run the code
  - pandas
  - seaborn
  - openpyxl
  - geopandas
  - pyogrio
  - geopy
  - contextily
  - pyarrow
  - esda
  - splot
  - xarray
  - rioxarray
  - datashader
  - geocube
  - osmnx
  - xvec
  - tobler
  - h3-py
  - pyinterpolate
  - astropy
  # infrastructure
  - ipykernel
  - jupyter-cache
  - pip
  - pip:
      - git+https://github.com/pysal/libpysal.git@main
      - git+https://github.com/sjsrey/pointpats.git@knox
      - git+https://github.com/pysal/tobler.git@main
