# https://github.com/quarto-dev/quarto-actions/blob/main/examples/quarto-publish-example.yml
on:
  push:
    branches: main

name: Render and Publish

jobs:
    build-deploy:
        name: "Build and deploy"
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash -l {0}
        steps:
          - name: Check out repository
            uses: actions/checkout@v3

          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
                tinytex: false
                version: pre-release

          - name: Setup micromamba
            uses: mamba-org/setup-micromamba@v1
            with:
              environment-file: environment.yml
              micromamba-version: "latest"

          - name: Check and log the environment
            run: |
              python -c "import geopandas; geopandas.show_versions();"
              micromamba info
              micromamba list

          - name: Register kernel
            run: |
              python -m ipykernel install --user --name sds

          - name: Render Book project
            run: |
                quarto render --profile sds4sg
                quarto render --profile micro
                mkdir _site
                mv _site_micro _site/micro
                mv _site_sds4sg _site/sds4sg
                echo "<head><meta http-equiv='refresh' content='0; URL=sds4sg/index.html'></head>" > _site/index.html

          - name: Deploy
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./_site